<?php

/**
 * @file
 * Smart Login functionalities.
 *
 * Inspired by IN2PIRE (contact@inspire.vn).
 */

use Symfony\Component\HttpFoundation\RedirectResponse;

/**
 * Get admin theme for smart login.
 */
function smart_login_get_admin_theme() {
  static $theme = NULL;

  if (NULL === $theme) {
    $theme = \Drupal::config('smart_login.settings')->get('admin.theme');

    if (empty($theme) || 'default' == $theme) {
      $theme = \Drupal::config('system.theme')->get('admin');
    }
  }

  return $theme;
}

/**
 * Get destination for smart login.
 */
function smart_login_destination($path = NULL) {
  $destination = \Drupal::request()->get('destination', NULL);

  if (empty($path)) {
    $path = current_path();
  }

  if (path_is_admin($path)) {
    // Backend.
    $defaul_variable = 'admin.destination';
    $default_path = 'admin';
  }
  else {
    // Frontend.
    $defaul_variable = 'front.destination';
    $default_path = 'user';
  }

  if (empty($destination)) {
    $destination = \Drupal::config('smart_login.settings')->get($defaul_variable);
  }

  if ($destination == '' || $destination == 'user/login' || $destination == 'admin/login') {
    $destination = $default_path;
  }

  return $destination;
}

/**
 * Alter form and inject css.
 */
function _smart_login_form_alter(&$form, &$form_state) {
  $adminTheme = smart_login_get_admin_theme();
  $cssFile = drupal_get_path('module', 'smart_login') . '/css/' . $adminTheme . '.css';

  if (file_exists($cssFile)) {
    $form['#attached']['css'][$cssFile] = [
      'type' => 'file',
      'group' => CSS_THEME,
      'weight' => 1000,
    ];
  }
}

/**
 * Alter user_login() form.
 *
 * @see user_login()
 * @see smart_login_user_login_submit()
 */
function smart_login_form_user_login_form_alter(&$form, &$form_state) {
  $form['#submit'][] = 'smart_login_user_login_submit';

  if (!path_is_admin(current_path())) {
    return;
  }

  _smart_login_form_alter($form, $form_state);

  $form['actions']['link'] = [
    '#type' => 'link',
    '#title' => t('Forgot password?'),
    '#href' => 'admin/password',
  ];
}

/**
 * Submit handler.
 *
 * @see smart_login_form_user_login_alter()
 */
function smart_login_user_login_submit($form, &$form_state) {
  $form_state['redirect'] = new RedirectResponse(url(smart_login_destination(), ['absolute' => TRUE]), 302);
}

/**
 * Alter user_pass() form.
 *
 * @see user_pass()
 * @see smart_login_user_pass_submit()
 */
function smart_login_form_user_pass_alter(&$form, &$form_state) {
  if (!path_is_admin(current_path())) {
    return;
  }

  _smart_login_form_alter($form, $form_state);

  $form['actions']['link'] = [
    '#type' => 'link',
    '#title' => t('Login'),
    '#href' => 'admin/login',
  ];

  $form['#submit'][] = 'smart_login_user_pass_submit';
}

/**
 * Submit handler.
 *
 * @see smart_login_form_user_pass_alter()
 * @see smart_login_form_user_login_block_alter()
 */
function smart_login_user_pass_submit(&$form, &$form_state) {
  $form_state['redirect'] = new RedirectResponse(url('admin/login', ['absolute' => TRUE]), 302);
}

/**
 * Alter system_site_information_settings() form.
 *
 * @see smart_login_form_system_site_information_settings_submit()
 */
function smart_login_form_system_site_information_settings_alter(&$form, &$form_state) {
  $moduleConfig = \Drupal::config('smart_login.settings');

  $form['error_page']['site_403']['#default_value'] = $moduleConfig->get('page.403');
  $form['#submit'][] = 'smart_login_form_system_site_information_settings_submit';
}

function smart_login_form_system_site_information_settings_submit($form, $form_state) {
  $siteConfig = \Drupal::config('system.site');
  $moduleConfig = \Drupal::config('smart_login.settings');

  $siteConfig->set('page.403', 'error/403')->save();
  $moduleConfig->set('page.403', $form_state['values']['site_403'])->save();
}
